%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.24.4

-ifndef(anycable).
-define(anycable, true).

-define(anycable_gpb_version, "3.24.4").

-ifndef('DISCONNECTRESPONSE_PB_H').
-define('DISCONNECTRESPONSE_PB_H', true).
-record('DisconnectResponse',
        {status                         % = 1, {enum,'Status'} (optional)
        }).
-endif.

-ifndef('COMMANDRESPONSE_PB_H').
-define('COMMANDRESPONSE_PB_H', true).
-record('CommandResponse',
        {status,                        % = 1, {enum,'Status'} (optional)
         disconnect,                    % = 2, bool (optional)
         stop_streams,                  % = 3, bool (optional)
         streams = [],                  % = 4, [string]
         transmissions = []             % = 5, [string]
        }).
-endif.

-ifndef('COMMANDMESSAGE_PB_H').
-define('COMMANDMESSAGE_PB_H', true).
-record('CommandMessage',
        {command,                       % = 1, string (optional)
         identifier,                    % = 2, string (optional)
         connection_identifiers,        % = 3, string (optional)
         data                           % = 4, string (optional)
        }).
-endif.

-ifndef('CONNECTIONRESPONSE_PB_H').
-define('CONNECTIONRESPONSE_PB_H', true).
-record('ConnectionResponse',
        {status,                        % = 1, {enum,'Status'} (optional)
         identifiers,                   % = 2, string (optional)
         transmissions = []             % = 3, [string]
        }).
-endif.

-ifndef('CONNECTIONREQUEST_PB_H').
-define('CONNECTIONREQUEST_PB_H', true).
-record('ConnectionRequest',
        {path,                          % = 1, string (optional)
         headers = []                   % = 2, [{map,string,string}]
        }).
-endif.

-ifndef('DISCONNECTREQUEST_PB_H').
-define('DISCONNECTREQUEST_PB_H', true).
-record('DisconnectRequest',
        {identifiers,                   % = 1, string (optional)
         subscriptions = [],            % = 2, [string]
         path,                          % = 3, string (optional)
         headers = []                   % = 4, [{map,string,string}]
        }).
-endif.

-endif.
